-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      stages: [commit]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: debug-statements
        stages: [commit]
    -   id: flake8
        args: [--max-line-length=100]
        stages: [commit, manual]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.760
  hooks:
    - id: mypy
      stages: [commit, manual]
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      args: [--check]
      stages: [commit, manual]
